configuration 
{n
    font_family = Inter Light
    font_size = 16
    icon_theme = Tela-dark

    # color of windows
    #background = 0xCF0e64cc
    background = 0xCF011242
    # color of search bar, border and delimiter
    base = 0xCF0e47cc
    # border of search bar
    alternate_base = 0xFF39a5e3

    # accent
    accent = 0xFF07edf5
    accent_secondary = 0xff000000

    # bright_text
    bright_text = 0xFF05fad9

    # text of results
    text = 0xFF39a5e3

    rounding_large = 20
    rounding_small = 10
}

